### ISSUE TITLE
try to load in esp32 s3

### ISSUE THREAD

**Issue by shiryu55** [PPUC/ZeDMD#63]
supposedly loaded the firmware corresponding to my s3, ZeDMD-S3-N16R8_256x64 by this command line.
esptool --chip esp32s3 write_flash 0x0 ZeDMD.bin
I finished the firmware loading process correctly.

no response from the panels

**Comment by mkalkbrenner** [comment]
Are the wires correct? External Power supply for the panels?

**Comment by shiryu55** [comment]
![captura](https://github.com/user-attachments/assets/9b561aad-5bef-4048-90a2-5ff9945d505e)

I have it connected this way, plus the pins on the panel with a PC power supply
However, with the normal ESP32 programmed with the app, the panels work perfectly, so it is not a power problem.
It could be a firmware loading mode problem on the esp32 s3. I'm out of ideas.

**Comment by shiryu55** [comment]
![image](https://github.com/user-attachments/assets/7a9f104e-c772-44a7-bd5f-56c63626d96c)
As you can see in this other screenshot, I have no problem with the old esp32. 
perform firmware upload with ZeDMD_Updater.

It's something related to the S3 firmware or the way to load it.

**Comment by mkalkbrenner** [comment]
Are you sure that your S3 is a N16R8?

**Comment by shiryu55** [comment]
![image](https://github.com/user-attachments/assets/1f14541e-cac8-4a74-9de2-9f106096c22e)

**Comment by shiryu55** [comment]
0532042018040028018160004138ESP0V203

**Comment by shiryu55** [comment]
![image](https://github.com/user-attachments/assets/056deecf-3d87-44b0-88de-0547828a7dd4)

**Comment by shiryu55** [comment]
I don't know if you could try your compilation  https://github.com/PPUC/ZeDMD/releases/download/v3.6.0/ZeDMD-S3-N16R8_256x64.zip with an S3.
or some step-by-step guide on how to compile it myself
I tried to compile the source version 3.6 , platformio.ini modify [platformio]
default_envs = S3-N16R8_256x64
but it generates a 300kb firm, I don't know what I'm doing wrong

**Comment by mkalkbrenner** [comment]
try to build from 'main' branch, not 3.6.0

**Comment by mkalkbrenner** [comment]
Or flash this build:
https://gitlab-ee.intern.jarltech.de/cms/shop/-/merge_requests/2908

**Comment by shiryu55** [comment]
compile the main version and then 3.6 with the same result

**Comment by shiryu55** [comment]
![image](https://github.com/user-attachments/assets/1d3d9af4-526f-46ca-9a55-73ec061a1375)

**Comment by shiryu55** [comment]
the link is not right 
Anyway, could you try the firm 3.60 that you compiled for the s3 and can you confirm how it works in case I make a mistake or is it the compiled file?

**Comment by shiryu55** [comment]
a build guide would be great

**Comment by shiryu55** [comment]
Recompile the main version with the new changes, I'm still the same doesn't show any signs of life the panels.

**Comment by gustavoalara** [comment]
Hi @mkalkbrenner 

Same for me, I'm trying to load the firmware to the same S3 Shiryu55 uses. The result are the same. No problem uploading using the right USB conector on the S3 but when connecting to the left connector the panel doesn't show anything and the ESP32 continuosly connects and disconnects on Windows.

**Comment by mkalkbrenner** [comment]
S3 support is still experimental and has known issues, especially with USB. If you want to test it, you should build and flash the latest version of the main branch. That could be done from VSCode with platformio plugin or via the platformio command line tool. Or download the latest github action artifact and flash it using the the esptool:
https://github.com/PPUC/ZeDMD/actions/runs/11259693865
If you don't know how to do that, it might be better to wait for a release.

**Comment by shiryu55** [comment]
I recently saw the new revision, 4.0.  I loaded it for now on my S3 without connecting to the panel, how could I check the configuration web interface from the PC? to see how it works.

**Comment by mkalkbrenner** [comment]
we had an issue with the bootloader in the bin files for S3. Should be fixed now.

**Comment by riyadchowdhury** [comment]
Btw in the above screenshot C pin is connected to GPIO46 but if you look at https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA/blob/master/src/platforms/esp32s3/esp32s3-default-pins.hpp C pin is actually on GPIO 3. I was having issues until I connected 3 to GPIO3 on a esp32-s3

**Comment by shiryu55** [comment]
Steps followed, pin by pin with Dupont following this diagram
![image](https://github.com/user-attachments/assets/a37a8859-32da-45ee-af7d-3759b19341f5)

up the updater to 4.8.1
loaded with the command

esptool --chip esp32s3 write_flash 0x0 ZeDMD.bin


![image](https://github.com/user-attachments/assets/1edb82da-0379-41b8-a605-4f3c57535508)

the panels are not responding”

**Comment by shiryu55** [comment]
“Hello Markus,

I’ve tested the new firmware version (4.0.2) with the ESP32, and everything is perfect; the improvement in smoothness is very noticeable.

However, with the S3, I’m still having issues and can’t get anything to display on the matrices.

These are the steps I’m following:
	1.	This is the pin assignment I’ve set up (photo attached).
	2.	I connect the USB to the left port of the S3 and load the firmware using the latest version of esptool (4.8.1)
	3.	The firmware seems to load correctly (screenshot attached).
	4.	I connect the USB to the right port of the S3. But nothing is displayed on the screen.”



![image](https://github.com/user-attachments/assets/7f7ef8cb-b7f6-408a-a526-d110e3ea5aa4)![image](https://github.com/user-attachments/assets/9c73e57e-96e5-4b0a-b2ac-4b3f0fb1ceb3)
![image](https://github.com/user-attachments/assets/fb17b974-15f8-4001-ae7d-f0735976d03b)

**Comment by mkalkbrenner** [comment]
Meanwhile we tested so much with different variations of the S3.
Ensure that you use libzedmd 0.7.6 and ZeDMD 4.1.0.

**Comment by shiryu55** [comment]
Hello, could you detail the step-by-step process for uploading to S3 in case I make any unusual mistakes?

As for libzedmd, I can’t test it because no information appears on the panels, as I explained to you earlier.

**Comment by shiryu55** [comment]
Hello Markus, after countless attempts and tests, it turns out there was a cold solder joint on the OE pin. Everything is now working correctly.

**Comment by mkalkbrenner** [comment]
Thanks for your feedback!
